services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - 25432:5432
    volumes:
     #数据文件本地的存放位置（启动后会在当前目录下创建mount，用来存放数据库文件）
     - ./mount:/var/lib/postgresql/data
    environment:
     - PGDATA=/var/lib/postgresql/data/pgdata
     #用户名 可自行更改
     - POSTGRES_USER=lv_admin
     #密码 可自行更改
     - POSTGRES_PASSWORD=123456
     - POSTGRES_DB=lv_friends
    networks:
      default:
        ipv4_address: 172.22.4.13
    restart: always
      
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.4.0/24
          gateway: 172.22.4.1